version: 0.1

phases:
  build:
    commands:
      - node --version && npm --version
      - cp config.yml.example config.yml
      - npm install
      - node_modules/.bin/cdk synth
cache:
  paths:
    - 'node_modules/**/*'
